version: '3.9'

networks:
    laravel12_vue3_inertia_tailwind_network:

services:
    php:
        build:
            args:
                uid: "${UID:-1000}"
                gid: "${GID:-1000}"
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
            - "3000:3000"
        networks:
            - laravel12_vue3_inertia_tailwind_network
    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - laravel12_vue3_inertia_tailwind_network
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel12_vue3_inertia_tailwind_network
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "8080:8080"
        networks:
            - laravel12_vue3_inertia_tailwind_network
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - laravel12_vue3_inertia_tailwind_network
